# Generated by Django 3.0.3 on 2020-03-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_url', models.URLField(help_text='The URL to be monitored.', unique=True)),
                ('interval', models.DurationField(default='0:20:0')),
                ('response_code', models.CharField(default=201, max_length=4)),
            ],
        ),
    ]
