# Generated by Django 3.0.4 on 2020-03-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlcheck', '0002_auto_20200304_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='interval',
            field=models.CharField(max_length=4),
        ),
    ]
