# Generated by Django 3.0.4 on 2020-03-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlcheck', '0003_auto_20200304_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='interval',
            field=models.IntegerField(max_length=4),
        ),
    ]
