# Generated by Django 3.0.4 on 2020-03-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlcheck', '0007_auto_20200305_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2020-03-05 07:58:45'),
        ),
        migrations.AlterField(
            model_name='url',
            name='updated_at',
            field=models.DateTimeField(blank=True, default='2020-03-05 07:58:45'),
        ),
    ]
