# Generated by Django 3.0.4 on 2020-03-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlcheck', '0008_auto_20200305_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2020-03-05 08:00:57'),
        ),
        migrations.AlterField(
            model_name='url',
            name='updated_at',
            field=models.DateTimeField(blank=True, default='2020-03-05 08:00:57'),
        ),
    ]
