# Generated by Django 3.0.4 on 2020-03-09 20:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('urlcheck', '0017_auto_20200309_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 9, 20, 10, 22, 347246, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='url',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 9, 20, 10, 22, 347270, tzinfo=utc)),
        ),
    ]
